-- Migration number: 0002 	 2025-04-22T21:24:18.293Z
INSERT INTO consumption (category, title, attribution, year, current) VALUES
	('Books', 'Unassimilable: An Asian Diasporic Manifesto for the 21st Century', 'Bianca Mabute-Louie', 2025, true),
	('Books', 'The Year of Magical Thinking', 'Joan Didion', 2025, false),
	('Books', 'Living in Data', 'Jer Thorp', 2025, false),
	('Books', 'Killing Rage: Ending Racism', 'bell hooks', 2025, false),
	('Books', 'All About Love: New Visions', 'bell hooks', 2025, false),
	('Books', 'Time Is a Mother', 'Ocean Vuong', 2025, false),
	('Books', 'The Message', 'Ta-Nehisi Coates', 2025, false),
	('Books', 'Anthropocene Reviewed', 'John Green', 2024, false),
	('Books', 'The Stranger', 'Albert Camus', NULL, false),
	('Books', 'Crying in H Mart', 'Michelle Zauner', NULL, false),
	('Books', 'Data Feminism', 'Catherine D''Ignazio and Lauren Klein', NULL, false),
	('Books', 'How Charts Lie: Getting Smarter about Visual Information', 'Alberto Cairo', NULL, false),
	('Film', 'Frances Ha', NULL, 2025, false),
	('Film', 'Arrival', NULL, 2025, false),
	('Film', 'The Good Shepherd', NULL, 2025, false),
	('Film', 'Patriots Day', NULL, 2025, false),
	('Film', 'Marvelous and the Black Hole', NULL, 2025, false),
	('Film', 'Always Be My Maybe', NULL, 2025, false),
	('Film', 'The Half of It', NULL, 2025, false),
	('Film', 'Marriage Story', NULL, 2025, false),
	('Film', 'Unbroken', NULL, 2025, false),
	('Film', 'Take Out', NULL, 2025, false),
	('Film', 'Closing Dynasty', NULL, 2025, false),
	('Film', 'To All the Boys: Always and Forever', NULL, 2025, false),
	('Film', 'To All the Boys: P.S. I Still Love You', NULL, 2025, false),
	('Film', 'The Fault in Our Stars', NULL, 2025, false),
	('Film', 'Before We Go', NULL, 2025, false),
	('Film', 'World War Z', NULL, 2025, false),
	('Film', 'White House Down', NULL, 2025, false),
	('Film', 'Sorry to Bother You', NULL, 2025, false),
	('Film', 'Uncharted', NULL, 2025, false),
	('Film', '127 Hours', NULL, 2025, false),
	('Film', 'Anora', NULL, 2025, false),
	('Film', 'Transformers: Dark of the Moon', NULL, 2025, false),
	('Film', 'Transformers: Revenge of the Fallen', NULL, 2025, false),
	('Film', 'Transformers', NULL, 2025, false),
	('Film', 'Pacific Rim', NULL, 2025, false),
	('Film', 'Battleship', NULL, 2025, false),
	('Film', 'The Help', NULL, 2025, false),
	('Film', 'The Cider House Rules', NULL, 2025, false),
	('Film', 'Life of Pi', NULL, 2025, false),
	('Film', 'Almost Famous', NULL, 2025, false),
	('Film', 'Eternal Sunshine of the Spotless Mind', NULL, 2025, false),
	('Film', '42', NULL, 2025, false),
	('Film', 'The Breakfast Club', NULL, 2025, false),
	('Film', 'Perfect Days', NULL, 2025, false),
	('Film', 'Interstellar', NULL, 2024, false),
	('Film', 'Midway', NULL, 2024, false),
	('Film', 'The Hunger Games: Mockingjay — Part 2', NULL, 2024, false),
	('Film', 'The Hunger Games: Mockingjay — Part 1', NULL, 2024, false),
	('Film', 'The Hunger Games: Catching Fire', NULL, 2024, false),
	('Film', 'The Hunger Games', NULL, 2024, false),
	('Film', 'Legally Blonde', NULL, 2024, false),
	('Film', 'Clueless', NULL, 2024, false),
	('Film', 'Love in Taipei', NULL, 2024, false),
	('Film', 'Bottoms', NULL, 2024, false),
	('Film', 'The Lego Movie', NULL, 2024, false),
	('Film', 'Power Rangers (2017)', NULL, 2024, false),
	('Film', 'The Edge of Seventeen', NULL, 2024, false),
	('Film', 'The Perks of Being a Wallflower', NULL, 2024, false),
	('Film', 'A Family Affair', NULL, 2024, false),
	('Film', 'Inside Out 2', NULL, 2024, false),
	('Film', 'Dìdi', NULL, 2024, false),
	('Film', 'Return to Seoul', NULL, 2024, false),
	('Film', 'Past Lives', NULL, 2024, false),
	('Film', 'The Boy and the Heron', NULL, 2024, false),
	('Film', 'Midsommar', NULL, 2023, false),
	('Film', 'Barbie', NULL, 2023, false),
	('Film', 'Oppenheimer', NULL, 2023, false),
	('Film', 'Spider-Man: Across the Spider-Verse', NULL, 2023, false),
	('Film', 'Everything Everywhere All at Once', NULL, 2023, false),
	('Film', 'The Grand Budapest Hotel', NULL, 2023, false),
	('Film', 'Knives Out', NULL, 2023, false),
	('Film', 'Guardians of the Galaxy Vol. 3', NULL, 2023, false),
	('Film', 'Ant-Man and the Wasp: Quantumania', NULL, 2023, false),
	('Film', 'Mean Girls', NULL, NULL, false),
	('Film', 'World Trade Center', NULL, NULL, false),
	('Film', 'Loving Vincent', NULL, NULL, false),
	('Film', 'Glory', NULL, NULL, false),
	('Film', 'Bao', NULL, NULL, false),
	('Film', '1917', NULL, NULL, false),
	('Film', 'To All the Boys I''ve Loved Before', NULL, NULL, false),
	('Film', 'Hidden Figures', NULL, NULL, false),
	('Film', 'Inside Out', NULL, NULL, false),
	('Film', 'Turning Red', NULL, NULL, false),
	('Film', 'Soul', NULL, NULL, false),
	('Film', 'Up', NULL, NULL, false),
	('Film', 'WALL-E', NULL, NULL, false),
	('Film', 'Ratatouille', NULL, NULL, false),
	('Film', 'Cars', NULL, NULL, false),
	('Film', 'The Incredibles', NULL, NULL, false),
	('Film', 'Finding Nemo', NULL, NULL, false),
	('Film', 'Monsters, Inc.', NULL, NULL, false),
	('Film', 'Toy Story 2', NULL, NULL, false),
	('Film', 'A Bug''s Life', NULL, NULL, false),
	('Film', 'Toy Story', NULL, NULL, false),
	('Film', 'Spider-Man: Into the Spider-Verse', NULL, NULL, false),
	('Film', 'The Amazing Spider-Man 2', NULL, NULL, false),
	('Film', 'The Amazing Spider-Man', NULL, NULL, false),
	('Film', 'Spider-Man 3', NULL, NULL, false),
	('Film', 'Spider-Man 2', NULL, NULL, false),
	('Film', 'Spider-Man', NULL, NULL, false),
	('Film', 'Black Panther: Wakanda Forever', NULL, NULL, false),
	('Film', 'Thor: Love and Thunder', NULL, NULL, false),
	('Film', 'Doctor Strange in the Multiverse of Madness', NULL, NULL, false),
	('Film', 'Spider-Man: No Way Home', NULL, NULL, false),
	('Film', 'Eternals', NULL, NULL, false),
	('Film', 'Shang-Chi and the Legend of the Ten Rings', NULL, NULL, false),
	('Film', 'Black Widow', NULL, NULL, false),
	('Film', 'Spider-Man: Far From Home', NULL, NULL, false),
	('Film', 'Avengers: Endgame', NULL, NULL, false),
	('Film', 'Captain Marvel', NULL, NULL, false),
	('Film', 'Ant-Man and the Wasp', NULL, NULL, false),
	('Film', 'Avengers: Infinity War', NULL, NULL, false),
	('Film', 'Black Panther', NULL, NULL, false),
	('Film', 'Thor: Ragnarok', NULL, NULL, false),
	('Film', 'Spider-Man: Homecoming', NULL, NULL, false),
	('Film', 'Guardians of the Galaxy Vol. 2', NULL, NULL, false),
	('Film', 'Doctor Strange', NULL, NULL, false),
	('Film', 'Captain America: Civil War', NULL, NULL, false),
	('Film', 'Ant-Man', NULL, NULL, false),
	('Film', 'Avengers: Age of Ultron', NULL, NULL, false),
	('Film', 'Guardians of the Galaxy', NULL, NULL, false),
	('Film', 'Captain America: The Winter Soldier', NULL, NULL, false),
	('Film', 'Thor: The Dark World', NULL, NULL, false),
	('Film', 'Iron Man 3', NULL, NULL, false),
	('Film', 'The Avengers', NULL, NULL, false),
	('Film', 'Captain America: The First Avenger', NULL, NULL, false),
	('Film', 'Thor', NULL, NULL, false),
	('Film', 'Iron Man 2', NULL, NULL, false),
	('Film', 'The Incredible Hulk', NULL, NULL, false),
	('Film', 'Iron Man', NULL, NULL, false),
	('Film', 'Ender''s Game', NULL, NULL, false),
	('Film', 'All Quiet on the Western Front (2022)', NULL, NULL, false),
	('Film', 'The Florida Project', NULL, NULL, false),
	('Film', 'Dunkirk', NULL, NULL, false),
	('Film', 'Lady Bird', NULL, NULL, false),
	('Film', 'Eighth Grade', NULL, NULL, false),
	('Film', 'The Truman Show', NULL, NULL, false),
	('Film', 'Ferris Bueller''s Day Off', NULL, NULL, false),
	('Film', 'Crazy Rich Asians', NULL, NULL, false),
	('Film', 'Taxi Driver', NULL, NULL, false),
	('Film', 'The Godfather', NULL, NULL, false),
	('Film', 'The Godfather Part II', NULL, NULL, false),
	('Film', 'Goodfellas', NULL, NULL, false),
	('Film', 'One Flew Over the Cuckoo''s Nest', NULL, NULL, false),
	('Film', 'Rocky IV', NULL, NULL, false),
	('Film', 'Rocky III', NULL, NULL, false),
	('Film', 'Rocky II', NULL, NULL, false),
	('Film', 'Rocky', NULL, NULL, false),
	('Film', 'Rambo III', NULL, NULL, false),
	('Film', 'Rambo: First Blood Part II', NULL, NULL, false),
	('Film', 'First Blood', NULL, NULL, false),
	('Film', 'Downfall', NULL, NULL, false),
	('Film', 'Fury', NULL, NULL, false),
	('Film', 'Saving Private Ryan', NULL, NULL, false),
	('Film', 'Inglorious Basterds', NULL, NULL, false),
	('Film', 'Full Metal Jacket', NULL, NULL, false),
	('Film', 'Letters from Iwo Jima', NULL, NULL, false),
	('Film', 'Flags of Our Fathers', NULL, NULL, false),
	('Film', 'Hacksaw Ridge', NULL, NULL, false),
	('Film', 'Pearl Harbor', NULL, NULL, false),
	('Film', 'Enemy at the Gates', NULL, NULL, false),
	('Film', 'Patton', NULL, NULL, false),
	('Film', 'Spirited Away', NULL, NULL, false),
	('Film', 'Shawshank Redemption', NULL, NULL, false),
	('Film', 'Good Will Hunting', NULL, NULL, false),
	('Film', 'Forrest Gump', NULL, NULL, false),
	('Film', 'Cast Away', NULL, NULL, false),
	('Film', 'A Beautiful Mind', NULL, NULL, false),
	('Film', 'School of Rock', NULL, NULL, false),
	('Film', 'Lincoln', NULL, NULL, false),
	('Shows', 'Veep', NULL, 2025, false),
	('Shows', 'Masters of the Air', NULL, 2024, false),
	('Shows', 'Moral Orel', NULL, 2024, false),
	('Shows', 'American Born Chinese', NULL, 2023, false),
	('Shows', 'Last Chance High', NULL, NULL, false),
	('Shows', 'Quiet on Set: The Dark Side of Kids TV', NULL, NULL, false),
	('Shows', 'Jet Lag: The Game', NULL, NULL, false),
	('Shows', 'School Babysitters', NULL, NULL, false),
	('Shows', 'Attack on Titan', NULL, NULL, false),
	('Shows', 'Atypical', NULL, NULL, false),
	('Shows', 'Silicon Valley', NULL, NULL, false),
	('Shows', 'Band of Brothers', NULL, NULL, false),
	('Shows', 'The Pacific', NULL, NULL, false),
	('Documentaries', 'AlphaGo', 'DeepMind', NULL, false),
	('Documentaries', 'The Fallen of World War II', 'Neil Halloran', NULL, false),
	('Talks', 'Rap Theory & Practice: an Introduction', 'Lupe Fiasco', NULL, false),
	('Talks', 'Web Without Walls', 'Dan Abramov', NULL, false),
	('Talks', 'Rethinking reactivity', 'Rich Harris', NULL, false),
	('Talks', 'Computer, build me an app', 'Rich Harris', NULL, false),
	('Talks', 'The beauty of data visualization', 'David McCandless', NULL, false),
	('Talks', 'What the heck is the event loop anyway?', 'Philip Roberts', NULL, false),
	('Talks', 'Design is a Search Problem', 'Mike Bostock', NULL, false),
	('Papers', 'Humanities Approaches to Graphical Display', 'Johanna Drucker', NULL, false),
	('Papers', 'Anti-Semitism as Skill: Rudolf Virchow''s "Schulstatistik" and the Racial Composition of Germany', 'Andrew Zimmerman', NULL, false),
	('Papers', 'Situated Knowledges: The Science Question in Feminism and the Privilege of Partial Perspective', 'Donna Haraway', NULL, false),
	('Journalism', 'The Blast Effect', 'The Washington Post', NULL, false),
	('Journalism', 'The Firefighter With O.C.D. and the Vaccine He Believed Would Kill Him', 'The New York Times', NULL, false),
	('Journalism', 'The Anti-Social Century', 'The Atlantic', NULL, false),
	('Journalism', 'The Agony of Texting With Men', 'The Atlantic', NULL, false),
	('Journalism', 'The Militia and the Mole', 'ProPublica', NULL, false),
	('Journalism', 'The Good Whale', 'The New York Times', NULL, false),
	('Journalism', 'The Deserter', 'The New York Times', NULL, false),
	('Journalism', 'Searching for Maura', 'The Washington Post', NULL, false),
	('Journalism', 'More than 1,800 congressmen once enslaved Black people. This is who they were, and how they shaped the nation.', 'The Washington Post', NULL, false),
	('Journalism', 'Machine Bias', 'ProPublica', NULL, false),
	('Journalism', 'How does ''Hamilton,'' the non stop, hip-hop Broadway sensation tap rap''s master rhymes to blur musical lines?', 'The Wall Street Journal', NULL, false),
	('Essays', 'The Worst Magazine In America', 'Nathan J. Robinson', NULL, false),
	('Essays', 'AI: The New Aesthetics of Fascism', 'Gareth Watkins', NULL, false),
	('Essays', 'Surely You''re a Creep, Mr. Feynman', 'Leila McNeill', NULL, false),
	('Essays', 'The "Blob" Is Furious About Gaza. But That''s Not Enough.', 'Josef Burton', NULL, false);